Update secretscan.yaml

diff --git a/.github/workflows/secretscan.yaml b/.github/workflows/secretscan.yaml
--- a/.github/workflows/secretscan.yaml
+++ b/.github/workflows/secretscan.yaml
@@ -24,20 +24,15 @@ jobs:
         run: pip install truffleHog
 
       - name: Install jq
-        run: sudo apt-get install jq
+        run: sudo apt-get install -y jq
 
       - name: Run TruffleHog Scan
         run: trufflehog git --json . > trufflehog-report.json 2>&1 || true
 
-      - name: Check File Existence and Size
-        run: |
-          if [ -f trufflehog-report.json ]; then
-            echo "File exists and size is $(stat -c%s trufflehog-report.json) bytes."
-          else
-            echo "File does not exist."
-          fi
+      - name: Validate JSON
+        run: jq . trufflehog-report.json > /dev/null || echo "Invalid JSON format"
 
-      - name: View TruffleHog JSON Report
+      - name: Print JSON Content
         run: cat trufflehog-report.json
 
       - name: Convert TruffleHog JSON report to HTML
